### ISSUE TITLE
CSS Styling Components

### ISSUE THREAD

**Issue by motosharpley** [TheDevPath/googleMaps-offline-navigator#108]
Adjust client component styling to provide uniform experience throughout. 
Use app mock-ups [here](https://sketch.cloud/s/Om3Dk) for inspiration and have fun! 

**Item list of priority components**

- [x] Style search feature for map view #181 
- [x] Add hamburger icon and directions icon to map view #179 
- [ ] style profile route #184
- [x] Map view icons #170 
- [x] Make App Nav Icons #166

**Comment by alicepalazzolo** [comment]
@motosharpley do we need new mock ups here with the new color scheme to go with the logo/ icon ?

**Comment by motosharpley** [comment]
@alicepalazzolo yes That would be great!

**Comment by jkwening** [comment]
Issues clean up - noted tasks have their own issues.
