### ISSUE TITLE
Master Issue - Initial Standup

### ISSUE THREAD

**Issue by jkwening** [TheDevPath/googleMaps-offline-navigator#17]
Hi - the purpose of this issue is to give a bird's eye view of what is currently being worked on, how it relates to other tasks, and a place to note what needs to be done next.

Please add tasks as needed even if you're not planning on working it so others can have a starting point. If possible, for big tasks, please break into modular subtasks for clarity and ease of tracking. Keep the listed tasks here simple descriptors, the issues themselves should have detailed information regarding the task; for context purposes and allowing someone else to work on the task or continue where you left off.

#### Design
- [ ] wire frames (#11) / mockups (#13)
    - [x] draft overall structure of the app (#16)
    - [ ] identify components
    - [ ] finalize structure and features list for version 1 standup (#16)
    - [ ] app landing page
    - [ ] search for location & results view
    - [ ] directions view
    - [ ] drop pin view
    - [ ] map view
    - [ ] save view (pin/directions)
    - [ ] list of saved pins/directions view
    - [ ] login page (low priority?)
- [ ] story board (#12)
    - [ ] draft storyboard
    - [ ] app logo (#8)
    - [ ] app color scheme (#10)
        - [ ] general app views
        - [ ] connection notification updates

#### Preact
- [x] create "hello world" preact app as base (#2)
- [ ] prototype (#13) - dependent on finalizing wire frames, mockups, and storyboard
    - [ ] app landing page
    - [ ] map view
    - [ ] search for location & results view
    - [ ] directions view

## Backend
- [x] setup basic express server (#1)
- [ ] connect MongoDB and app server using Node.js driver (alternative is mongoose driver)
    - [ ] setup mongodb and config folder (#25)
- [ ] create RESTful API
    - [ ] determine needed routes
- [ ] outline database model for MongoDB (#30)
    - [ ] saved dropped pins
    - [ ] saved directions
    - [ ] search history

#### Documentation
- [x] create contribution guidelines (#5)
    - [ ] create an outline
- [ ] app wiki (#6)
- [ ] draft install readme (#9)

**Comment by tophergates** [comment]
What are you all thinking in terms of how the app will be structured? I'm sure you all have your opinions on how best to organize the directory structure, but I think we should all come to a consensus on what that should be.

Just my two cents:

```
/ (root)
├── /config
|   └── dev.config.js // development environment configs
|   └── index.js // export appropriate configs based on process.env.NODE_ENV
|   └── prod.config.js // production configs
├── /client // Preact boilerplate (frontend)
|   └── /public
|       └── favicon.ico
|       └── index.html
|       └── manifest.json
|   └── /src
|       └── /assets
|       └── /components
|       └── index.js // client entry-point
|       └── serviceWorker.js
|   └── .gitignore
|   └── package.json // client dependencies
├── /models
    └── User.js
    └── etc...
├── /routes
|   └── api.js
|   └── etc...
├── index.js // server entry-point
├── package.json // server dependencies
```

I'm not sure whether you all feel this type of client/server architecture will work well or not, but this structure seems to help compartmentalize backend from frontend and allows them to carry their own dependencies independently from each other. Thoughts?

**Comment by motosharpley** [comment]
Ya your headed in the same direction as I am. I have commented the express pull request with a number of theses structural aspects so that we will end up with exactly the style of client/server architecture you are proposing and I'm am working my way through the preact client side pull now. Once i get those two merged in it should become a lot easier to break out small feature tasks and get more people pull request opportunities. One other thing I like to do is set up a proxy script between the two so that as we are developing locally we can keep our api calls clean and not have to do a lot of work to go to production.

**Comment by tophergates** [comment]
You've probably already seen this, but it looks like Preact uses Webpack devServer under the hood. We can setup a [proxy](https://github.com/developit/preact-cli/wiki/Config-Recipes#setting-proxy-for-dev-server-using-config-directly) to the API server with a really minor configuration. 🎉

**Comment by jkwening** [comment]
Closing this since we have a road map and other resources to better track what's going on.
